name: Deploy Voting App

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Compose Validation
        run: docker compose config

      - name: SSH Deploy

        uses: appleboy/ssh-action@v1.0.3

        with:

          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          script: |

            cd /home/ubuntu/voting-app

            git pull origin main

            docker compose down

            docker compose up -d --build
